# Generated by Django 4.1 on 2024-05-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to='images')),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ManyToManyField(to='www.brand')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('userphoto', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ManyToManyField(to='www.model')),
            ],
        ),
    ]
