# Generated by Django 4.1 on 2024-05-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='brand',
        ),
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
