# Generated by Django 5.0.6 on 2024-05-09 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0003_comment_remove_model_brand_delete_brand_delete_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="text",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "like",
                    models.BooleanField(choices=[(True, "Like"), (False, "Unlike")]),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.comment"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.user"
                    ),
                ),
            ],
        ),
    ]
