# Generated by Django 4.1 on 2024-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_alter_user_text_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='unlikes_count',
            field=models.IntegerField(default=0),
        ),
    ]
