# Generated by Django 4.1 on 2024-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_comment_likes_count_comment_unlikes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unlikes_count',
        ),
        migrations.AddField(
            model_name='like',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='unlikes_count',
            field=models.IntegerField(default=0),
        ),
    ]
